<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>9c94bfae-a894-4d79-8c62-b2b31e5d2c16</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.13">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.13.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Homefy.Application\Homefy.Application.csproj" />
		<ProjectReference Include="..\Homefy.Infrastructure\Homefy.Infrastructure.csproj" />
	</ItemGroup>

</Project>
